<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework></PropertyGroup>
  <ItemGroup><ProjectReference Include="../../src/Client.Launcher/Client.Launcher.csproj" /></ItemGroup>
  <ItemGroup><PackageReference Include="Avalonia.Headless" Version="12.1.3" /></ItemGroup>
</Project>
